#!/usr/bin/env python
"""doc_sync.py — 从关键模块提取 docstring 并生成 Markdown API 文档。

用法:
    python tools/doc_sync.py
    python tools/doc_sync.py --output docs/API_REFERENCE.md
    python tools/doc_sync.py --modules infra,config,strategy
"""

from __future__ import annotations

import argparse
import ast
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional

# ── 路径设置 ──────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

# ── 默认扫描模块 ──────────────────────────────────────────
DEFAULT_MODULES = [
    "infra",
    "config",
    "strategy",
    "risk",
    "governance",
    "evaluation",
    "strategy_judgment",
    "lifecycle",
]

# ── 跳过的目录名 ──────────────────────────────────────────
SKIP_DIRS = {"__pycache__", "archive", "tests", "tools", ".git", ".ci", ".github"}


# ── AST 提取 ──────────────────────────────────────────────


def _get_docstring(node: ast.AST) -> str:
    """安全获取 AST 节点的 docstring。"""
    doc = ast.get_docstring(node)
    return doc.strip() if doc else ""


def extract_from_file(filepath: str) -> Dict:
    """从单个 Python 文件提取类和函数的 docstring。

    返回:
        {
            "module_doc": str,
            "classes": [{"name": str, "doc": str, "methods": [{"name": str, "doc": str}]}],
            "functions": [{"name": str, "doc": str}],
        }
    """
    result: Dict = {"module_doc": "", "classes": [], "functions": []}
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            source = f.read()
    except (OSError, UnicodeDecodeError):
        return result

    try:
        tree = ast.parse(source, filename=filepath)
    except SyntaxError:
        return result

    result["module_doc"] = _get_docstring(tree)

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            cls_info = {
                "name": node.name,
                "doc": _get_docstring(node),
                "methods": [],
            }
            for item in ast.iter_child_nodes(node):
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    method_doc = _get_docstring(item)
                    if method_doc:
                        cls_info["methods"].append(
                            {"name": item.name, "doc": method_doc}
                        )
            result["classes"].append(cls_info)

        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            func_doc = _get_docstring(node)
            if func_doc:
                result["functions"].append({"name": node.name, "doc": func_doc})

    return result


def scan_module(module_dir: str) -> List[Dict]:
    """扫描一个模块目录下所有 Python 文件。"""
    items: List[Dict] = []
    for root, dirs, files in os.walk(module_dir):
        # 原地过滤跳过的目录
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fname in sorted(files):
            if not fname.endswith(".py"):
                continue
            fpath = os.path.join(root, fname)
            rel = os.path.relpath(fpath, module_dir).replace("\\", "/")
            info = extract_from_file(fpath)
            if info["module_doc"] or info["classes"] or info["functions"]:
                items.append({"file": rel, **info})
    return items


# ── Markdown 生成 ─────────────────────────────────────────


def generate_markdown(module_data: Dict[str, List[Dict]]) -> str:
    """将提取结果渲染为 Markdown 文本。"""
    lines: List[str] = [
        "# API Reference",
        "",
        "> Auto-generated by `tools/doc_sync.py`. Do not edit manually.",
        "",
    ]

    for mod_name in sorted(module_data.keys()):
        files = module_data[mod_name]
        if not files:
            continue
        lines.append(f"## {mod_name}")
        lines.append("")

        for entry in files:
            lines.append(f"### `{entry['file']}`")
            lines.append("")

            if entry["module_doc"]:
                lines.append(entry["module_doc"])
                lines.append("")

            for cls in entry["classes"]:
                lines.append(f"#### class `{cls['name']}`")
                lines.append("")
                if cls["doc"]:
                    lines.append(cls["doc"])
                    lines.append("")
                for m in cls["methods"]:
                    lines.append(f"- **`{m['name']}`** — {m['doc']}")
                if cls["methods"]:
                    lines.append("")

            for func in entry["functions"]:
                lines.append(f"- **`func:{func['name']}`** — {func['doc']}")
            if entry["functions"]:
                lines.append("")

    return "\n".join(lines)


# ── CLI ───────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract docstrings and generate API reference markdown."
    )
    parser.add_argument(
        "--output",
        default=os.path.join(BASE_DIR, "docs", "API_REFERENCE.md"),
        help="Output markdown file path (default: docs/API_REFERENCE.md)",
    )
    parser.add_argument(
        "--modules",
        default=None,
        help="Comma-separated list of modules to scan (default: all key modules)",
    )
    args = parser.parse_args()

    # 确定要扫描的模块
    if args.modules:
        modules = [m.strip() for m in args.modules.split(",") if m.strip()]
    else:
        modules = DEFAULT_MODULES

    # 扫描
    module_data: Dict[str, List[Dict]] = {}
    for mod_name in modules:
        mod_dir = os.path.join(BASE_DIR, mod_name)
        if not os.path.isdir(mod_dir):
            print(f"[WARN] Module directory not found, skipping: {mod_dir}")
            continue
        print(f"[INFO] Scanning module: {mod_name}")
        module_data[mod_name] = scan_module(mod_dir)

    # 生成 Markdown
    md_content = generate_markdown(module_data)

    # 写入文件
    output_path = args.output
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"[DONE] API reference written to: {output_path}")


if __name__ == "__main__":
    main()
